[5542] Adicionando um card de curso sobre o git e o github
Kelwinpin/CursosTreinamento pull request #6
Opened 2023-02-27 22:15 UTC by Kelwinpin

-  Adicionando mais um card de curso da alura, este é referente ao git e o github.

2023-02-27 22:18 UTC, Kelwinpin commented
- Adicionei mais um curso da alura, este referente ao curso de git e github.

2023-02-28 14:37 UTC, robsonfacil requested changes

2023-02-28 14:37 UTC, robsonfacil commented on .prettierrc
> +    "trailingComma": "es5",
Pq não usar uma versão do Ecmascript mais recente como o ES2021 ou até a ultima ES2022?

2023-02-28 14:37 UTC, robsonfacil commented on .eslintrc.js
> +    "es2021": true,
no eslint vc colocou es2021... só precisa mudar no prettier

2023-02-28 14:37 UTC, robsonfacil commented on .prettierrc
> +    "printWidth": 80
Remova essa linha, deixa pro eslint cuidar disso.

2023-02-28 14:37 UTC, robsonfacil commented on package.json
> +    "eslint": "^8.35.0",
É impressão minha, ou esta faltando as dependências do Prettier?

2023-02-28 16:33 UTC, Kelwinpin commented on package.json
> +    "eslint": "^8.35.0",
Tudo foi resolvido no commit [1d595cc](https://github.com/Kelwinpin/CursosTreinamento/pull/6/commits/1d595cca7a5591c60b067a4bb7465b4ecfe96c58)

2023-03-01 13:28 UTC, merged